name: Auto-Reply to Issues

on:
  issues:
    types: [opened]

jobs:
  auto-reply:
    runs-on: ubuntu-latest
    steps:
      - name: Reply to issue based on type
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const issueTitle = issue.title.toLowerCase();
            const issueBody = issue.body || '';
            const labels = issue.labels.map(label => label.name);
            let issueComment = '';

            // Determine issue type and set appropriate response
            if (labels.includes('bug') || issueTitle.includes('bug:')) {
              issueComment = `**Thank you for reporting this bug!**
              We appreciate you taking the time to provide detailed information about the issue you've encountered. Our team will investigate this bug and work on a fix as soon as possible.
              Thank you for helping us improve our software!`;
              
            } else if (labels.includes('enhancement') || issueTitle.includes('request:')) {
              issueComment = `**Thank you for your feature request!**
              We're excited to hear your ideas for improving our project. Feature requests from our community are valuable and help shape the future direction of our software.
              Thank you for contributing to our project's growth!`;
              
            } else if (labels.includes('question') || issueTitle.includes('question:')) {
              issueComment = `**Thank you for your question!**
              We're here to help you get the most out of our software. Questions from users help us identify areas where our documentation can be improved.
              We appreciate your engagement with our project!`;
              
            } else {
              // Generic response for unclassified issues
              issueComment = `**Thank you for opening this issue!**
              We appreciate you taking the time to contribute to our project. To help us assist you better, please:
              Our team will review and respond soon. Thank you for using our software!`;
            }

            // Post the comment
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueComment
            });

            // Add reaction to show the bot has processed the issue
            await github.rest.reactions.createForIssue({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              content: 'eyes'
            });
